### ISSUE TITLE
This library is awesome!

### ISSUE THREAD

**Issue by danaugrs** [EthanStandel/preact-signal-store#13]
I just want to say that deepsignal is absolutely awesome! I'm using it with [Deno Fresh](https://fresh.deno.dev/) (preact) and it's the most performant and ergonomic way of managing state I've ever used. Thanks for building it!

**Comment by EthanStandel** [comment]
Glad to hear it's being enjoyed! Fresh is actually a use-case I never tested, but I bet of people who are heavily integrated into _Preact's_ ecosystem, Fresh is pretty common. Have you had any problems getting it supported by Deno and is there anything that would help that integration, or is hosting it on GH & NPM all that is necessary?

**Comment by danaugrs** [comment]
It worked pretty seamlessly - Deno recently added support for NPM modules - so it was just a couple of imports!
