### ISSUE TITLE
Type definitions broken

### ISSUE THREAD

**Issue by lewisfm** [EthanStandel/preact-signal-store#16]
TypeScript cannot load this library's type definitions, with the following error:
```
Could not find a declaration file for module '@deepsignal/preact'. '[...]/@deepsignal/preact/dist/lib.es.js' implicitly has an 'any' type.
  There are types at '[...]/@deepsignal/preact/dist/lib.d.ts', but this result could not be resolved when respecting package.json "exports". The '@deepsignal/preact' library may need to update its package.json or typings.
```

**Comment by EthanStandel** [comment]
Sorry to be so late back to this @doinkythederp. I used TypeScript's recommendation preference on how to expose types, not via `"exports"` but via just a `"type"` property directly.

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I'd ask you more information about your environment, but @patricklizon actually already opened a PR for the issue and linked the Webpack docs describing this preference.

https://webpack.js.org/guides/package-exports/

**Comment by EthanStandel** [comment]
New version released, closing out. Feel free to reopen if you're still having problems.
