### ISSUE TITLE
Boolean values are not working

### ISSUE THREAD

**Issue by mike-live** [EthanStandel/preact-signal-store#25]
In case of false is assigned to property inside deepSignal it will removes property from deepSignal object.

Suggestion to fix this issue:
Line 112 `https://github.com/EthanStandel/deepsignal/blob/main/packages/core/src/core.ts`
```ts
if (deep[key]) {
```
change to 
```ts
if (deep.hasOwnProperty(key)) {
```

Line 133 
```ts
if (!payload[key]) {
```
change to
```ts
if (!payload.hasOwnProperty(key)) {
```

**Comment by EthanStandel** [comment]
Fantastic catch! I've added a test validating the issue and then patched it. Version 4.1.0 should have this issue cleaned up!
